apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::283826630039:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7C2XYHOBVRBV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::283826630039:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::283826630039:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7C2XYHOBVRBV\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n  rolearn: arn:aws:iam::283826630039:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-08-31T13:38:18Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"10335","uid":"e67cda19-1e4a-4588-952e-f678686cc3c1"}}
  creationTimestamp: "2021-08-31T13:38:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "10951"
  uid: e67cda19-1e4a-4588-952e-f678686cc3c1
